Add docs for node discovery via DNS
axieinfinity/ronin-documentation pull request #212
Opened 2023-09-05 03:12 UTC by phuctd95

2023-09-05 03:19 UTC, huyngopt1994 approved these changes

2023-09-07 05:23 UTC, RodinGolodin requested changes
Please address the comments.

2023-09-07 05:23 UTC, RodinGolodin commented on docs/node-operators/setup/mainnet/validator.md
> +  An alternative to set the boot node is to use  node discovery via DNS (see [REP-0005](https://github.com/axieinfinity/REPs/blob/main/REP-0005.md)). In the `.env` file
to set -> to setting

2023-09-07 05:23 UTC, RodinGolodin commented on docs/node-operators/setup/mainnet/validator.md
> +  An alternative to set the boot node is to use  node discovery via DNS (see [REP-0005](https://github.com/axieinfinity/REPs/blob/main/REP-0005.md)). In the `.env` file
In the `.env` file, make the following changes:

2023-09-07 05:23 UTC, RodinGolodin commented on docs/node-operators/setup/mainnet/validator.md
> +  -  Append the `--discovery.dns enrtree://...` at the end of `RONIN_PARAMS` line
Append `--discovery.dns enrtree://...` at the end of the `RONIN_PARAMS` line.

2023-09-07 05:23 UTC, RodinGolodin commented on docs/node-operators/setup/mainnet/validator.md
> +  We provide the DNS tree link for node operators.
Can "DNS tree link" be replaced with "DNS node list"? The sentence will then look like this: "We provide a DNS node list for node operators:"

2023-09-07 05:23 UTC, RodinGolodin commented on docs/node-operators/setup/mainnet/validator.md
> +  - Saigon Testnet: `enrtree://AJCNIAXQIPO55NW3QE2NUBBDMPYZDOQUCAEUS65NHQFMUUFES5KOW@saigon.nodes.roninchain.com`
Add an empty line before this line.

2023-09-07 06:05 UTC, RodinGolodin approved these changes

2023-09-07 06:06 UTC, merged